build: off
version: dev-{build}
shallow_clone: false
clone_folder: C:\projects\php-cs-fixer

cache:
    - '%APPDATA%\Composer'

install:
    - choco install -y php
    - SET PATH=C:\tools\php;%PATH%
    - cd C:\tools\php
    - copy php.ini-production php.ini
    - echo date.timezone="UTC" >> php.ini
    - echo memory_limit=512M >> php.ini
    - echo extension_dir=ext >> php.ini
    - echo extension=php_curl.dll >> php.ini
    - echo extension=php_openssl.dll >> php.ini
    - cd C:\tools
    - appveyor DownloadFile https://getcomposer.org/composer.phar
    - appveyor DownloadFile https://phar.phpunit.de/phpunit.phar
    - git config --global github.accesstoken 5e7538aa415005c606ea68de2bbbade0409b4b8c

before_test:
    - cd C:\projects\php-cs-fixer
    - php C:\tools\composer.phar update --no-interaction --no-progress --optimize-autoloader --prefer-stable --no-ansi

test_script:
    - cd C:\projects\php-cs-fixer
    - php C:\tools\phpunit.phar --verbose
    - php php-cs-fixer --diff --dry-run -v fix
