version: 2

jobs:
    build:
        macos:
            xcode: '9.0'
        steps:
            - checkout

            - save_cache:
                key: dependency-cache
                paths:
                    - ~/.composer
                    - ~/Library/Caches/Homebrew

            - run: brew update
            - run: brew install php72
            - run: echo "memory_limit = 512M" > $(brew --prefix)/etc/php/7.3/conf.d/memory.ini
            - run: curl -sS https://getcomposer.org/installer | php
            - run: php composer.phar global show hirak/prestissimo -q || php composer.phar global require --no-interaction --no-progress --optimize-autoloader hirak/prestissimo
            - run: php composer.phar install --optimize-autoloader --no-interaction --no-progress --no-suggest
            - run: vendor/bin/phpunit
            - run: PHP_CS_FIXER_FUTURE_MODE=1 php php-cs-fixer --diff --dry-run -v fix
